# -*- coding: utf-8 -*-
"""chialuka-igbo-llm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/Lukas-technoledge/caf12e566661eabf9f660227d57c7a24/chialuka-igbo-llm.ipynb

# **Manual Accuracy Evaluation**

Words are manually rated on a Likert scale (1–5):

1 = Strongly Agree (Accurate)

2 = Agree (Mostly Accurate)

3 = Neutral (Unclear/Partial)

4 = Disagree (Somewhat Inaccurate)

5 = Strongly Disagree (Inaccurate)
"""

import pandas as pd

#data = pd.read_excel("Chialuka-Igbo-LLM.xlsx")
# data.to_csv("Chialuka-Igbo-LLM.xlsx.csv", index=False)

#print(data.head())

# Read the CSV back to display its head
ling_data = pd.read_excel("Chialuka-Igbo-LLM.xlsx")
ling_data.head()

# Export a smaller sample for human evaluation
sample_data = ling_data.sample(n=100, random_state=67)
sample_data.to_excel("sample_data_for_human_evaluation_100_67.xlsx", index=False)

"""Generate translation for the Igbo words in the sample file"""

import openai

# Optional: set your API key here or via environment variable OPENAI_API_KEY
openai.api_key = ""

def translate_igbo_to_english(text):
    """
    Use GPT-4o-mini to translate Igbo to English
    """
    try:
        response = openai.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": "You are a helpful translator that translates Igbo to English."},
                {"role": "user", "content": f"Translate this Igbo sentence to English:\n{text}. Output only the result with no additional information"}
            ],
            temperature=0.2
        )
        return response.choices[0].message.content.strip()
    except Exception as e:
        return f"Error: {e}"

# Example usage
if __name__ == "__main__":
    igbo_input = "efere"
    english_output = translate_igbo_to_english(igbo_input)
    print(f"Igbo: {igbo_input}")
    print(f"English: {english_output}")

import openai
import pandas as pd
from tqdm.auto import tqdm

# Optional: set your API key here or via environment variable
openai.api_key = "sk-*****"

def translate_igbo_to_english(text):
    """
    Use GPT-4o-mini to translate Igbo to English
    """
    try:
        response = openai.chat.completions.create(
            model="gpt-4o",
            messages=[
                {"role": "system", "content": "You are a helpful translator that translates Igbo to English."},
                {"role": "user", "content": f"Translate this Igbo sentence to English:\n{text}. Output only the result with no additional information"}
            ],
            temperature=0.2
        )
        return response.choices[0].message.content.strip()
    except Exception as e:
        return f"Error: {e}"

if __name__ == "__main__":
    # Example DataFrame; replace this with your actual sample_data
    sample_data = pd.read_excel("sample_data_for_human_evaluation.xlsx")

    # Initialize progress bar for pandas
    tqdm.pandas()

    # Apply the translation function to each 'word' in the DataFrame
    sample_data['translation'] = sample_data['word'].progress_apply(translate_igbo_to_english)

    # Display or save the translated DataFrame
    print(sample_data)
    sample_data.to_excel('translated_data_gpt_4o.xlsx', index=False)
    # sample_data.to_csv('translated_data_gpt_4o.csv', index=False)

from google.colab import drive
drive.mount('/content/drive')

sample_data.to_excel('translated_data_gpt_4o.xlsx', index=False)

"""## **Semantic Similarity via Word Embeddings**"""

!pip install -q sentence-transformers

from sentence_transformers import SentenceTransformer, util

# Load a multilingual model that supports Igbo
model = SentenceTransformer('distiluse-base-multilingual-cased')

#translate



# Compute embeddings
df_sample['word_embedding'] = df_sample['word'].apply(lambda x: model.encode(x, convert_to_tensor=True))
df_sample['definition_embedding'] = df_sample['definitions'].apply(lambda x: model.encode(x, convert_to_tensor=True))

# Compute cosine similarity
df_sample['cosine_similarity'] = df_sample.apply(
    lambda row: util.cos_sim(row['word_embedding'], row['definition_embedding']).item(),
    axis=1
)

# View results
df_sample[['word', 'definitions', 'cosine_similarity']].head()

"""Here is an explanation of each line in the code cell `EdA3IYKdKG89`:

*   `!pip install -q sentence-transformers`: This line uses a Colab magic command (`!`) to run a shell command. It installs the `sentence-transformers` library, which is used for generating sentence embeddings. The `-q` flag makes the installation quiet, meaning it won't print as much output.
*   `from sentence_transformers import SentenceTransformer, util`: This line imports the necessary classes and functions from the `sentence-transformers` library: `SentenceTransformer` for loading the pre-trained model and `util` for utility functions like cosine similarity calculation.
*   `model = SentenceTransformer('distiluse-base-multilingual-cased')`: This line loads a pre-trained sentence transformer model. The model `'distiluse-base-multilingual-cased'` is a multilingual model that can handle text in many different languages, including Igbo.
*   `df_sample = data_csv[['word', 'definitions']].dropna().sample(100, random_state=42).reset_index(drop=True)`: This line prepares a sample of your data for analysis.
    *   `data_csv[['word', 'definitions']]`: Selects the 'word' and 'definitions' columns from the `data_csv` DataFrame.
    *   `.dropna()`: Removes any rows that have missing values in either of these columns.
    *   `.sample(100, random_state=42)`: Randomly selects 100 rows from the remaining data. `random_state=42` ensures that you get the same sample every time you run the code.
    *   `.reset_index(drop=True)`: Resets the DataFrame index after sampling and drops the old index.
*   `df_sample['word_embedding'] = df_sample['word'].apply(lambda x: model.encode(x, convert_to_tensor=True))`: This line computes the sentence embedding for each 'word' in the `df_sample` DataFrame.
    *   `.apply(lambda x: ...)`: Applies a function to each element in the 'word' column.
    *   `model.encode(x, convert_to_tensor=True)`: Uses the loaded `SentenceTransformer` model to encode the word `x` into a numerical vector (embedding). `convert_to_tensor=True` ensures the output is a PyTorch tensor.
    *   `df_sample['word_embedding'] = ...`: Stores the resulting embeddings in a new column called 'word_embedding'.
*   `df_sample['definition_embedding'] = df_sample['definitions'].apply(lambda x: model.encode(x, convert_to_tensor=True))`: This line does the same as the previous line but for the 'definitions' column, creating a new column called 'definition_embedding' with the embeddings of the definitions.
*   `df_sample['cosine_similarity'] = df_sample.apply(lambda row: util.cos_sim(row['word_embedding'], row['definition_embedding']).item(), axis=1)`: This line calculates the cosine similarity between the word embedding and the definition embedding for each row.
    *   `.apply(lambda row: ..., axis=1)`: Applies a function to each row of the DataFrame.
    *   `util.cos_sim(row['word_embedding'], row['definition_embedding'])`: Calculates the cosine similarity between the word embedding and the definition embedding for the current row. Cosine similarity is a measure of how similar two non-zero vectors are.
    *   `.item()`: Extracts the scalar value from the resulting tensor.
    *   `df_sample['cosine_similarity'] = ...`: Stores the calculated cosine similarity in a new column called 'cosine_similarity'.
*   `df_sample[['word', 'definitions', 'cosine_similarity']].head()`: This line displays the first few rows of the `df_sample` DataFrame, showing the original word and definition along with their calculated cosine similarity.
"""



import openai

# Optional: set your API key here or via environment variable OPENAI_API_KEY
openai.api_key = "sk-******"

def translate_igbo_to_english(text):
    """
    Use GPT-4o-mini to translate Igbo to English
    """
    try:
        response = openai.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": "You are a helpful translator that translates Igbo to English."},
                {"role": "user", "content": f"Translate this Igbo sentence to English:\n{text}. Output only the result with no additional information"}
            ],
            temperature=0.2
        )
        return response.choices[0].message.content.strip()
    except Exception as e:
        return f"Error: {e}"

# Example usage
if __name__ == "__main__":
    igbo_input = "efere"
    english_output = translate_igbo_to_english(igbo_input)
    print(f"Igbo: {igbo_input}")
    print(f"English: {english_output}")

"""Machine eval of LLM translations"""

import openai
import pandas as pd
from tqdm.auto import tqdm

# Optional: set your API key here or via environment variable
openai.api_key = "sk-****"

sample_data = pd.read_excel("translated_data_gpt_4o_eval.xlsx")

sample_data

"""compare the definition with the translated text and provide a score from 0 to 5, where 0 completely different meaning  to 5 signifying exact match in terms of meaning"""

definition = sample_data['definitions'][25]
translation = sample_data['translation'][25]

response = openai.chat.completions.create(
model="gpt-4o-mini",
messages=[
                {"role": "system", "content": "You are a helpful translator that translates Igbo to English."},
                {"role": "user", "content": f"compare the {definition} with the translated {translation}and provide a score from 0 to 5, where 0 completely different meaning to 5 signifying exact match in terms of meaning. Note that the definition may contain alternative meanings, so consider that when rating. Output only the score."}
          ],
            temperature=0.2
  )

score = response.choices[0].message.content.strip()

score